apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ template "dataloader.name" . }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "dataloader.name" . }}
    spec:
      containers:
      - name: gpii-dataloader
        image: "{{ .Values.image.repository }}@{{ .Values.image.checksum }}"
        command: [ '/app/scripts/deleteAndLoadSnapsets.sh' ]
        env:
        - name: GPII_COUCHDB_URL
          valueFrom:
            secretKeyRef:
              name: {{ template "dataloader.name" . }}
              key: couchdbUrl
      restartPolicy: OnFailure
