apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "dataloader.name" . }}
  labels:
    app: {{ template "dataloader.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "dataloader.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: gpii-dataloader
        image: "{{ .Values.image.repository }}@{{ .Values.image.checksum }}"
        command: [ '/app/scripts/deleteAndLoadSnapsets.sh' ]
        env:
        - name: GPII_COUCHDB_URL
          valueFrom:
            secretKeyRef:
              name: {{ template "dataloader.name" . }}
              key: couchdbUrl
      restartPolicy: OnFailure
