apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dataloader.name" . }}
  labels:
    app: {{ template "dataloader.name" . }}
type: Opaque
data:
  couchdbUrl: {{ template "dataloader.defaultsecret" .Values.couchdb.url }}
