apiVersion: v1
kind: Secret
metadata:
  name: {{ template "flowmanager.name" . }}
  labels:
    app: {{ template "flowmanager.name" . }}
type: Opaque
data:
  datasourceHostname: {{ template "flowmanager.defaultsecret" .Values.datasourceHostname }}
