{{- if .Values.enableStackdriverTrace }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "flowmanager.name" . }}-cloudtrace
  labels:
    app: {{ template "flowmanager.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  hosts:
  - cloudtrace.googleapis.com
  tls:
  - match:
    - sniHosts:
      - cloudtrace.googleapis.com
    route:
    - destination:
        host: cloudtrace.googleapis.com
{{- end }}
