apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
 name: "couchdb"
spec:
 host: "{{ template "couchdb.svcname" . }}.{{ .Release.Namespace }}.svc.cluster.local"
 trafficPolicy:
   tls:
     mode: DISABLE
