secretLists:
- name: istio-ingressgateway-certs
  namespace: istio-system
  secretlist:
  - name: flowmanager-tls
    namespace: gpii
  notify:
  - name: istio-ingressgateway
    namespace: istio-system
    type: deployment
