apiVersion: v1
kind: Secret
metadata:
  name: {{ template "flushtokens.name" . }}
  labels:
    app: {{ template "flushtokens.name" . }}
type: Opaque
data:
  couchdbUrl: {{ template "flushtokens.defaultsecret" .Values.couchdb.url }}
