apiVersion: v1
kind: Secret
metadata:
  name: {{ template "couchdb_prometheus_exporter.name" . }}
  labels:
    app: {{ template "couchdb_prometheus_exporter.name" . }}
type: Opaque
data:
  couchdbUsername: {{ template "couchdb_prometheus_exporter.defaultsecret" .Values.couchdb.username }}
  couchdbPassword: {{ template "couchdb_prometheus_exporter.defaultsecret" .Values.couchdb.password }}
