image:
  repository: gpii/ssl-cert-check
  tag: 0.0.1-gpii.0
  pullPolicy: IfNotPresent

## Set project_id for Stackdriver target project
# project_id: fake-project

## Default run schedule is twice a day
cronJobSchedule: "0 */12 * * *"

## Max amount of time for cron job to run
activeDeadlineSeconds: 60

## Renewal window for Let's Encrypt certificates starts 30 days before expiration,
## So if it is not renewed 29 days before, there is a high chance that something went wrong
renewalWindow: 29

certificates:
  ## Example certificate block
  #- host: google.com
  #  port: 443
