apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ssl-cert-check.name" . }}
  labels:
    app: {{ template "ssl-cert-check.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config: |
    {{ range .Values.certificates -}}
    {{ .host }} {{ .port }}
    {{ end }}
