apiVersion: v1
kind: Secret
metadata:
  name: {{ template "preferences.name" . }}
  labels:
    app: {{ template "preferences.name" . }}
type: Opaque
data:
  datasourceHostname: {{ template "preferences.defaultsecret" .Values.datasourceHostname }}
